server:
  port: 9000
spring:
  application:
    name: basis-zuul


eureka:
  client:
    register-with-eureka: true # 是否注册到注册中心
    fetch-registry: true # 是否从注册中心获取服务
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/  # 注册中心地址


management:
  endpoints:
    web:
      exposure:
        include: 'routes'



#zuul:
#  routes: #服务配置路由
##    user-service:
##      path: /user-service/**
##  prefix: /api #给网关路由添加前缀
#  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
#  add-host-header: true #设置为true重定向是会添加host请求头
#  retryable: true # 关闭重试机制
#  PreLogFilter:
#    pre:
#      disable: true #控制是否启用过滤器